### GET: /counter
### Возвращает счетчик
GET http://localhost:8081/counter
Connection: close


### POST: /counter
### Увеличивает счетчик на 1
POST http://localhost:8081/counter
Connection: close

### DELETE: /counter
### Уменьшает счетчик на значение, которое передается в заголовке «Subtraction-Value»
DELETE http://localhost:8081/counter
Connection: close
Subtraction-Value: 3


### POST: /counter/clear authorized user
### Сбрасывает счетчик.
### Для выполнения этого запроса должна быть cookie - «hh-auth», единственное условие - она должна быть длиннее 10 символов.
POST http://localhost:8081/counter/clear
Connection: close
Cookie:  squash=patisson; hh-auth=can_reset_counter; crocodile=alligator


### POST: /counter/clear unauthorized user
### Сбрасывает счетчик.
### Для выполнения этого запроса должна быть cookie - «hh-auth», единственное условие - она должна быть длиннее 10 символов.
POST http://localhost:8081/counter/clear
Connection: close
Cookie:  squash=patisson; hh-auth=can't; crocodile=alligator